FROM node:22

WORKDIR /app

ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV VITE_API_URL=http://52.67.41.3

COPY package*.json ./
RUN npm install

COPY . .

# Builda os arquivos Vite
RUN npm run build

EXPOSE 3000

# Roda o preview (modo produção do Vite)
CMD ["npm", "run", "prod"]
