name: priceasy
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/node_modules:/app/node_modules
    depends_on:
      - frontend
      - backend
    networks:
      - priceasy-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - priceasy-network

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=priceasy
    networks:
      - priceasy-network

  db:
    image: mysql:8.0.39
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: priceasy
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - priceasy-network

volumes:
  database-data:

networks:
  priceasy-network:
