FROM mcr.microsoft.com/playwright:v1.55.0-noble

ENV NODE_ENV=production
ENV PUPPETEER_SKIP_DOWNLOAD=true

RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm ci --include=dev && npm cache clean --force

COPY . .

EXPOSE 4000

CMD ["node", "index.js"]
