FROM mcr.microsoft.com/playwright:v1.55.0-noble

ENV NODE_ENV=production
ENV PUPPETEER_SKIP_DOWNLOAD=true

WORKDIR /app

COPY package*.json ./
RUN npm ci --include=dev && npm cache clean --force

COPY . .

EXPOSE 4000

CMD ["node", "index.js"]
